name: Build Wheels
on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install UV
        uses: astral-sh/setup-uv@v6
      
      - name: Pin Python Version
        run: uv python pin 3.9.13

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.4

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: wheelhouse/*.whl

  build-linux:
    runs-on: ubuntu-latest
    container:
      image: almalinux:8
    steps:
      - name: Install prerequisites
        run: |
          dnf -y install dnf-plugins-core epel-release
          dnf -y install 'dnf-command(config-manager)'
          dnf -y install git wget make cmake xz file which

      - name: Enable GCC 14 toolset
        run: |
          dnf -y install gcc-toolset-14 gcc-toolset-14-gcc-c++
          echo "source /opt/rh/gcc-toolset-14/enable" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install UV
        uses: astral-sh/setup-uv@v6
      - name: Pin Python Version
        run: uv python pin 3.9.13
      - name: Build wheels
        run:
          uv build -v
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux
          path: dist/*.whl